create table wuwa_substat_value
(
	id integer generated by default as identity
		constraint wuwa_substat_value_pk
			primary key,
	substat_number integer,
	value_number integer,
	value_desc varchar(8),
	value_desc_full varchar(20)
);

comment on table wuwa_substat_value is '鸣潮 声骸 副词条 数值档位';

comment on column wuwa_substat_value.substat_number is '副词条的编号：0~12';

comment on column wuwa_substat_value.value_number is '数值档位：0~7或0~3';

comment on column wuwa_substat_value.value_desc is '数值档位描述：百分比% 或 固定值+';

alter table wuwa_substat_value owner to icehe;

create unique index wuwa_substat_value_substat_number_value_number_uindex
	on wuwa_substat_value (substat_number, value_number);

INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (8, 0, 7, '10.5%', '暴击 10.5%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (88, 11, 7, '11.6%', '共鸣技能 11.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (50, 7, 1, '360', '生命固定值 360');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (36, 4, 3, '8.6%', '生命 8.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (93, 12, 4, '9.4%', '共鸣解放 9.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (85, 11, 4, '9.4%', '共鸣技能 9.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (84, 11, 3, '8.6%', '共鸣技能 8.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (79, 10, 6, '10.9%', '重击 10.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (77, 10, 4, '9.4%', '重击 9.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (45, 6, 0, '40', '防御固定值 40');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (76, 10, 3, '8.6%', '重击 8.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (69, 9, 4, '9.4%', '普攻 9.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (18, 2, 1, '7.1%', '攻击 7.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (10, 1, 1, '13.8%', '暴击伤害 13.8%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (56, 7, 7, '580', '生命固定值 580');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (71, 9, 6, '10.9%', '普攻 10.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (2, 0, 1, '6.9%', '暴击 6.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (54, 7, 5, '510', '生命固定值 510');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (43, 5, 2, '50', '攻击固定值 50');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (63, 8, 6, '11.6%', '共鸣效率 11.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (16, 1, 7, '21.0%', '暴击伤害 21.0%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (4, 0, 3, '8.1%', '暴击 8.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (14, 1, 5, '18.6%', '暴击伤害 18.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (96, 12, 7, '11.6%', '共鸣解放 11.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (86, 11, 5, '10.1%', '共鸣技能 10.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (89, 12, 0, '6.4%', '共鸣解放 6.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (33, 4, 0, '6.4%', '生命 6.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (83, 11, 2, '7.9%', '共鸣技能 7.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (66, 9, 1, '7.1%', '普攻 7.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (49, 7, 0, '320', '生命固定值 320');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (23, 2, 6, '10.9%', '攻击 10.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (29, 3, 4, '11.8%', '防御 11.8%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (52, 7, 3, '430', '生命固定值 430');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (9, 1, 0, '12.6%', '暴击伤害 12.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (51, 7, 2, '390', '生命固定值 390');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (95, 12, 6, '10.9%', '共鸣解放 10.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (62, 8, 5, '10.8%', '共鸣效率 10.8%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (46, 6, 1, '50', '防御固定值 50');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (38, 4, 5, '10.1%', '生命 10.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (82, 11, 1, '7.1%', '共鸣技能 7.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (15, 1, 6, '19.8%', '暴击伤害 19.8%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (81, 11, 0, '6.4%', '共鸣技能 6.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (58, 8, 1, '7.6%', '共鸣效率 7.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (72, 9, 7, '11.6%', '普攻 11.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (64, 8, 7, '12.4%', '共鸣效率 12.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (40, 4, 7, '11.6%', '生命 11.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (73, 10, 0, '6.4%', '重击 6.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (68, 9, 3, '8.6%', '普攻 8.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (20, 2, 3, '8.6%', '攻击 8.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (53, 7, 4, '470', '生命固定值 470');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (12, 1, 3, '16.2%', '暴击伤害 16.2%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (41, 5, 0, '30', '攻击固定值 30');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (44, 5, 3, '60', '攻击固定值 60');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (30, 3, 5, '12.8%', '防御 12.8%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (35, 4, 2, '7.9%', '生命 7.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (22, 2, 5, '10.1%', '攻击 10.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (27, 3, 2, '10.0%', '防御 10.0%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (80, 10, 7, '11.6%', '重击 11.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (57, 8, 0, '6.8%', '共鸣效率 6.8%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (5, 0, 4, '8.7%', '暴击 8.7%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (32, 3, 7, '14.7%', '防御 14.7%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (48, 6, 3, '70', '防御固定值 70');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (91, 12, 2, '7.9%', '共鸣解放 7.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (55, 7, 6, '540', '生命固定值 540');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (26, 3, 1, '9.0%', '防御 9.0%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (87, 11, 6, '10.9%', '共鸣技能 10.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (13, 1, 4, '17.4%', '暴击伤害 17.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (67, 9, 2, '7.9%', '普攻 7.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (6, 0, 5, '9.3%', '暴击 9.3%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (31, 3, 6, '13.8%', '防御 13.8%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (75, 10, 2, '7.9%', '重击 7.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (94, 12, 5, '10.1%', '共鸣解放 10.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (90, 12, 1, '7.1%', '共鸣解放 7.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (78, 10, 5, '10.1%', '重击 10.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (60, 8, 3, '9.2%', '共鸣效率 9.2%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (37, 4, 4, '9.4%', '生命 9.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (92, 12, 3, '8.6%', '共鸣解放 8.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (3, 0, 2, '7.5%', '暴击 7.5%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (7, 0, 6, '9.9%', '暴击 9.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (59, 8, 2, '8.4%', '共鸣效率 8.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (65, 9, 0, '6.4%', '普攻 6.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (17, 2, 0, '6.4%', '攻击 6.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (47, 6, 2, '60', '防御固定值 60');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (74, 10, 1, '7.1%', '重击 7.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (25, 3, 0, '8.1%', '防御 8.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (21, 2, 4, '9.4%', '攻击 9.4%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (1, 0, 0, '6.3%', '暴击 6.3%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (39, 4, 6, '10.9%', '生命 10.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (61, 8, 4, '10.0%', '共鸣效率 10.0%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (34, 4, 1, '7.1%', '生命 7.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (24, 2, 7, '11.6%', '攻击 11.6%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (11, 1, 2, '15.0%', '暴击伤害 15.0%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (28, 3, 3, '10.9%', '防御 10.9%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (42, 5, 1, '40', '攻击固定值 40');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (70, 9, 5, '10.1%', '普攻 10.1%');
INSERT INTO public.wuwa_substat_value (id, substat_number, value_number, value_desc, value_desc_full) VALUES (19, 2, 2, '7.9%', '攻击 7.9%');
