BEGIN;

CREATE TABLE IF NOT EXISTS public.wuwa_echo_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    substat1 BIGINT NOT NULL DEFAULT 0,
    substat2 BIGINT NOT NULL DEFAULT 0,
    substat3 BIGINT NOT NULL DEFAULT 0,
    substat4 BIGINT NOT NULL DEFAULT 0,
    substat5 BIGINT NOT NULL DEFAULT 0,
    substat_all BIGINT NOT NULL DEFAULT 0,
    s1_desc TEXT NOT NULL DEFAULT '',
    s2_desc TEXT NOT NULL DEFAULT '',
    s3_desc TEXT NOT NULL DEFAULT '',
    s4_desc TEXT NOT NULL DEFAULT '',
    s5_desc TEXT NOT NULL DEFAULT '',
    clazz TEXT NOT NULL DEFAULT '',
    user_id INTEGER NOT NULL DEFAULT 0,
    operator_id INTEGER NOT NULL DEFAULT 1,
    deleted INTEGER NOT NULL DEFAULT 0,
    tuned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT wuwa_echo_log_deleted_check CHECK (deleted IN (0, 1))
);

COMMENT ON TABLE public.wuwa_echo_log IS '鸣潮声骸完整调谐记录';
COMMENT ON COLUMN public.wuwa_echo_log.substat1 IS '第 1 个副词条编码';
COMMENT ON COLUMN public.wuwa_echo_log.substat2 IS '第 2 个副词条编码';
COMMENT ON COLUMN public.wuwa_echo_log.substat3 IS '第 3 个副词条编码';
COMMENT ON COLUMN public.wuwa_echo_log.substat4 IS '第 4 个副词条编码';
COMMENT ON COLUMN public.wuwa_echo_log.substat5 IS '第 5 个副词条编码';
COMMENT ON COLUMN public.wuwa_echo_log.substat_all IS '所有副词条低 13 位合集';
COMMENT ON COLUMN public.wuwa_echo_log.clazz IS '声骸套装或分类';
COMMENT ON COLUMN public.wuwa_echo_log.user_id IS '用户 ID';
COMMENT ON COLUMN public.wuwa_echo_log.deleted IS '软删除标记：0 未删除，1 已删除';
COMMENT ON COLUMN public.wuwa_echo_log.tuned_at IS '调谐发生时间';

CREATE TABLE IF NOT EXISTS public.wuwa_tune_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    substat INTEGER NOT NULL,
    value INTEGER NOT NULL,
    position INTEGER NOT NULL,
    echo_id INTEGER NOT NULL DEFAULT 0,
    user_id INTEGER NOT NULL DEFAULT 0,
    operator_id INTEGER NOT NULL DEFAULT 1,
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT wuwa_tune_log_substat_check CHECK (substat BETWEEN 0 AND 12),
    CONSTRAINT wuwa_tune_log_value_check CHECK (value BETWEEN 0 AND 7),
    CONSTRAINT wuwa_tune_log_position_check CHECK (position BETWEEN 0 AND 4),
    CONSTRAINT wuwa_tune_log_deleted_check CHECK (deleted IN (0, 1))
);

COMMENT ON TABLE public.wuwa_tune_log IS '鸣潮声骸副词条调谐记录';
COMMENT ON COLUMN public.wuwa_tune_log.substat IS '副词条类型编号，范围 0-12';
COMMENT ON COLUMN public.wuwa_tune_log.value IS '副词条档位编号，范围 0-7';
COMMENT ON COLUMN public.wuwa_tune_log.position IS '副词条孔位，范围 0-4';
COMMENT ON COLUMN public.wuwa_tune_log.echo_id IS '所属声骸 ID';
COMMENT ON COLUMN public.wuwa_tune_log.user_id IS '用户 ID';
COMMENT ON COLUMN public.wuwa_tune_log."timestamp" IS '记录时间';
COMMENT ON COLUMN public.wuwa_tune_log.deleted IS '软删除标记：0 未删除，1 已删除';

CREATE INDEX IF NOT EXISTS idx_wuwa_echo_log_deleted_updated_at
    ON public.wuwa_echo_log (deleted, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_wuwa_echo_log_user_id_deleted
    ON public.wuwa_echo_log (user_id, deleted);

CREATE INDEX IF NOT EXISTS idx_wuwa_echo_log_clazz_user_id_deleted
    ON public.wuwa_echo_log (clazz, user_id, deleted);

CREATE INDEX IF NOT EXISTS idx_wuwa_echo_log_substat_all
    ON public.wuwa_echo_log (substat_all);

CREATE INDEX IF NOT EXISTS idx_wuwa_echo_log_substat_tuple
    ON public.wuwa_echo_log (substat1, substat2, substat3, substat4, substat5);

CREATE INDEX IF NOT EXISTS idx_wuwa_tune_log_deleted_id
    ON public.wuwa_tune_log (deleted, id DESC);

CREATE INDEX IF NOT EXISTS idx_wuwa_tune_log_user_id_deleted
    ON public.wuwa_tune_log (user_id, deleted);

CREATE INDEX IF NOT EXISTS idx_wuwa_tune_log_echo_id_position_deleted
    ON public.wuwa_tune_log (echo_id, position, deleted);

CREATE INDEX IF NOT EXISTS idx_wuwa_tune_log_substat_deleted
    ON public.wuwa_tune_log (substat, deleted);

COMMIT;
